/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Sarahí
 */
public class printTutorados extends javax.swing.JFrame {

    /**
     * Creates new form printTutorados
     */
    public printTutorados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneImprimirTutorados = new javax.swing.JPanel();
        paneImpresion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaTutorados = new javax.swing.JList<>();
        lblTutorados = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        tfTutor = new java.awt.TextField();
        lblIconoImpresora = new javax.swing.JLabel();
        lblImprimir = new javax.swing.JLabel();
        lblTutorate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneImprimirTutorados.setBackground(new java.awt.Color(255, 255, 255));
        paneImprimirTutorados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        paneImpresion.setBackground(new java.awt.Color(255, 255, 255));
        paneImpresion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ListaTutorados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaTutorados);

        lblTutorados.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lblTutorados.setText("TUTORADOS");

        lblDocente.setText("Docente:");

        javax.swing.GroupLayout paneImpresionLayout = new javax.swing.GroupLayout(paneImpresion);
        paneImpresion.setLayout(paneImpresionLayout);
        paneImpresionLayout.setHorizontalGroup(
            paneImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneImpresionLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(lblDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneImpresionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneImpresionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTutorados)
                .addGap(69, 69, 69))
        );
        paneImpresionLayout.setVerticalGroup(
            paneImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneImpresionLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTutorados)
                .addGap(31, 31, 31)
                .addGroup(paneImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        lblIconoImpresora.setBackground(new java.awt.Color(204, 204, 204));
        lblIconoImpresora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconoImpresora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoImprimir_2.PNG"))); // NOI18N

        lblImprimir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblImprimir.setText("Imprimir");

        lblTutorate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2_3.PNG"))); // NOI18N

        javax.swing.GroupLayout paneImprimirTutoradosLayout = new javax.swing.GroupLayout(paneImprimirTutorados);
        paneImprimirTutorados.setLayout(paneImprimirTutoradosLayout);
        paneImprimirTutoradosLayout.setHorizontalGroup(
            paneImprimirTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneImprimirTutoradosLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(paneImprimirTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneImprimirTutoradosLayout.createSequentialGroup()
                        .addComponent(lblImprimir)
                        .addGap(33, 33, 33)))
                .addGap(114, 114, 114)
                .addComponent(paneImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lblTutorate)
                .addContainerGap())
        );
        paneImprimirTutoradosLayout.setVerticalGroup(
            paneImprimirTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneImprimirTutoradosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(paneImprimirTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneImprimirTutoradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneImprimirTutoradosLayout.createSequentialGroup()
                            .addComponent(paneImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneImprimirTutoradosLayout.createSequentialGroup()
                            .addComponent(lblIconoImpresora)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblImprimir)
                            .addGap(197, 197, 197)))
                    .addGroup(paneImprimirTutoradosLayout.createSequentialGroup()
                        .addComponent(lblTutorate)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(paneImprimirTutorados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(paneImprimirTutorados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printTutorados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printTutorados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printTutorados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printTutorados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printTutorados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaTutorados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblIconoImpresora;
    private javax.swing.JLabel lblImprimir;
    private javax.swing.JLabel lblTutorados;
    private javax.swing.JLabel lblTutorate;
    private javax.swing.JPanel paneImpresion;
    private javax.swing.JPanel paneImprimirTutorados;
    private java.awt.TextField tfTutor;
    // End of variables declaration//GEN-END:variables
}
